version: "3.9"
services:
  db:
    image: postgres:17
    container_name: biblio_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-biblio}
      POSTGRES_USER: ${POSTGRES_USER:-biblio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-biblio}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-biblio} -d $${POSTGRES_DB:-biblio}"]
      interval: 5s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: biblio_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  db_data:
  pgadmin_data:
